# Mettere qui i dati corretti per Twitter
TWITTER_CONSUMER_KEY = 'wuoBKI9skuAaW88B6UbtlzgN9'
TWITTER_CONSUMER_SECRET = '7h0TNdmrAaLHr0Sx5e72GMhVrGsWd0VybB0DIMtb2WFZ9ICLev'
TWITTER_ACCESS_TOKEN = '4796762962-HnlexzM7rbPHG73Uo2q9SFuZUqWWCIgNqcu3lwt'
TWITTER_ACCESS_TOKEN_SECRET = 'DpB6LHWMfSaeBVbmLo76bbBdKaAeeJdqRiFO7G2izKVDF'

# Mettere qui i dati corretti per Facebook
FACEBOOK_CONSUMER_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXX'
FACEBOOK_CONSUMER_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX'
FACEBOOK_ACCESS_TOKEN = 'EAAGOsWPoluQBAJPV5Wl3Td9qQYPKSc5cQbOXQ6NUYFbvqTbNrIkycDG20TtariSMsbyUvK45Goe71Xj6VEh6PFEIjwUdMUmmeKM00M8IKYvzgTB9DpRVxrdUF1wZC8IBS32IrBvT9n9MgOpn6ZAXt4QaGS60oRX98YrutZB4wZDZD'
FACEBOOK_ACCESS_TOKEN_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXXXX'

# Mettere qui i dati corretti per Linkedin
LINKEDIN_CONSUMER_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXX'
LINKEDIN_CONSUMER_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX'
LINKEDIN_ACCESS_TOKEN = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX'
LINKEDIN_ACCESS_TOKEN_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXXXX'
